@startuml CarePlanService Container Diagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
skinparam linetype polyline

title Doel dag 1

System_Ext(EHR, "EHR")
System_Boundary(CarePlanService, "Care Plan Service") {
    Container(FHIRStore, "FHIR Store", "HAPI FHIR", "Stores FHIR resources")
    Container(CareTeamService, "Care Team Service", "Golang", "Updates CareTeams based on CarePlans in the FHIR store")

    Rel(EHR, FHIRStore, "Accesses/Manages CarePlans", "HTTPS")
    Rel(FHIRStore, CareTeamService, "Notifies of CarePlan updates", "FHIR Subscription")
    Rel(CareTeamService, FHIRStore, "Updates CareTeam", "HTTP")
}
@enduml