@startuml careplan-careteam-management-overview
'https://plantuml.com/activity-diagram-beta
start
:Loop through all Tasks for CarePlan &
evaluate CareTeam membership(-period)
of Task.owner;
:Update CarePlan.activities;
:Update CareTeam;
:Notify CareTeam members 
(current and removed members);
stop
@enduml