@startuml careplan-careteam-management-overview
'https://plantuml.com/activity-diagram-beta
start
floating note left: Diagram not completed yet\nfor all possible\nstatus transitions
if (Task updated by Owner\nstatus accepted or\nin-progress or on-hold) then (yes)
if (Task last update by Requester\nstatus requested) then (yes)
  #LightGreen:Owner active member of CareTeam;
endif
else (no)
if (Task updated by Owner\nstatus completed or\nfailed) then (yes)
  #orange:Owner not active member of CareTeam;
  else (no)
    #Pink:Owner no member of CareTeam;
endif

endif
:Patch CarePlan.activities;
:Update CareTeam;
:Notify CareTeam members ;
stop
@enduml
