@startuml example1-retrievingdata
' box "organization A" #LightYellow
participant "autorizationserver-A" as asa order 40
participant "ehr-A" as ehra order 30
' end box
' box "organization B" #LightYellow
participant "autorizationserver-B" as asb order 60
participant "ehr-B" as ehrb order 50
' end box
' box "organization C" #LightYellow
participant "ehr-C" as ehrc order 20
actor "practitioner Charlie" as prc order 10
' end box
hide footbox

prc -> ehrc : I want to access Diabetes-\n data of patient-P
activate ehrc
ehrc -> ehrc : lookup reference/url\n of CarePlan in (local) Task


group get careplan/careteam at ehr-A
    ehrc -> asa : request access token (scope CarePlan/CareTeam for patient-P)
    deactivate ehrc
    activate asa
    asa -> asa : check if practitioners from\n organization-C are members\n of careteam
    asa -> asa : check local autorisations for\n careteam, organization-role\n on patient-P data
    asa -> ehrc : access token
    deactivate asa
    activate ehrc
    ehrc -> ehra : request careplan/careteam of patient-P
    deactivate ehrc
    activate ehra
    ehra -> ehrc : careplan/careteam of patient-P
    deactivate ehra
    activate ehrc
end

ehrc -> ehrc : lookup reference/url's of activities\n in careplan
ehrc -> asb : request access token (scope patient-P)
deactivate ehrc
activate asb
group  get careplan/careteam at ehr-A
    note over asb, ehra #White : autorizationserver-B initiating sub-proces\n "get careplan/careteam at ehr-A" 
end
asb -> asb : check if //practitioner Charlie//\n is (active/inactive) member\n of careteam
asb -> asb : check local autorisations for\n careteam, active-member-role\n on patient-P data
asb -> ehrc : access token
deactivate asb
activate ehrc
ehrc -> ehrb : request resources of patient-P
deactivate ehrc
activate ehrb
ehrb -> ehrc : resources of patient-P
deactivate ehrb
activate ehrc
ehrc -> prc : present data of patient-P
deactivate ehrc
@enduml