@startuml koppeltaal-medmij-uc-1

skinparam roundcorner 20
skinparam defaultFontName Arial 
hide footbox

!pragma teoz true

actor  Patient as "Vera"
actor  Doctor as "GP Dr. West"
participant  HIS as "gp-system"
participant  EHR1 as "ehr1"
participant  EHR2 as "ehr2"

Patient -> Doctor: My schoulder hurts 
Doctor -> Doctor: Perform anamnesis 
Doctor -> HIS: Create CarePlan-1\n for shoulder complaints
Doctor -> HIS: Create ServiceRequest-1\n for MRI scan

Doctor -> HIS: Search/select MRI services\n within 30km
HIS -> HIS: Create Tasks\n for ServiceRequest-1
HIS -> EHR1: POST plan-Task-1 (intent=plan)\n with focus ServiceRequest-1
EHR1 -> EHR1: Evaluate plan-Task-1,\n accept, start date May 1
EHR1 -> HIS: Notify & pull Task-1 update
HIS -> EHR2: POST plan-Task-2 (intent=plan)\n with focus ServiceRequest-1 
EHR2 -> EHR2: Evaluate plan-Task-2,\n accept, start date June 1
EHR2 -> HIS: Notify & pull Task-2 update
HIS -> Doctor: Show\n plan-Tasks
Doctor -> HIS: Select Task-1
HIS -> EHR1: Create/POST order-Task-3\n with focus ServiceRequest-1
EHR1 -> EHR1: Evaluate order-Task-3, accept
EHR1 -> HIS: Notify/pull order-Task-3
group opt
    HIS -> Patient: Is zh1 the new care provider\n for your shoulder complaints?\n(via (e)mail, like an account activation email)
    Patient -> HIS: Yes
end group

HIS -> HIS: Update CarePlan-1\n with zh1 as care provider
EHR1 -> Patient: Share your data with zh1\n with shoulder complaint care providers?\n (=general practitioner in CarePlan-1)?
Patient -> EHR1: Yes

@enduml
