.PHONY: gen-svg

gen-png:
	cat "usecase-homemonitoring-onboarding.puml" | docker run --rm -i aplr/plantuml -tpng > "usecase-homemonitoring-onboarding.png"

gen-svg:
	cat "usecase-homemonitoring-onboarding.puml" | docker run --rm -i aplr/plantuml > "usecase-homemonitoring-onboarding.svg"