@startuml overview-task-negotiation-1-2-3

autonumber
!pragma teoz true

box Care Provider 2
    actor "Practitioner" as Practitioner1
    participant "Care Plan Contributor" as CPC1
end box
box Care Provider 1
    participant "Care Plan Service" as CPS
end box

box Care Provider 3
    participant "Care Plan Contributor" as CPC2
    participant "Order mgnt" as EHR2
    actor "Practitioner" as Practitioner2
end box
hide footbox


activate Practitioner1
Practitioner1 -> CPC1 : Start Request\nreferral
& CPC1 -> CPS : Create Task:\n status requested,\n referring CarePlan\n and (Service-)Request
& CPS -> CPC2  : Notify Task created
& CPC2 -> EHR2  : Notify Task created
& EHR2 -> EHR2 : evaluate Task:\n <color #purple>(required data,\n <color #purple>capacity, etc)

& note over Practitioner2 #WhiteSmoke
Actions in <color #purple>purple
 are optional
end note

EHR2 -> CPC2 : Update Task:\n <color #purple>Need more information
& CPC2 -> CPS  : Update Task: \n <color #purple>add preliminary\n <color #purple> QuestionnaireResponse\n <color #purple>to Task.input
& CPS -> CPC1 : Notify Task update
& CPC1 -[#purple]> Practitioner1 : <color #purple>Present form\n<color #purple>(prefill data from EHR)

Practitioner1 -[#purple]> CPC1 : <color #purple>Complete form
& CPC1 -[#purple]> CPS : <color #purple>Update Task: Complete\n <color #purple>QuestionnaireResponse\n <color #purple>in Task.input
& CPS -[#purple]> CPC2 : <color #purple>Notify Task update
& CPC2 -[#purple]> EHR2 : <color #purple>Notify Task update

& EHR2 -> EHR2 : evaluate Task:\n status 'received'

CPC2 -> CPS : Update Task: \n status 'received'
& EHR2 -[#purple]> CPC2 : <color #purple>Notify Task update
& CPS -> CPC1 : Notify Task update
& CPC1 -> Practitioner1 : Your order has been received
& EHR2 -> Practitioner2 : present Task

deactivate Practitioner1

== waiting for Practitioner to accept ==
Practitioner2 -> EHR2 : Task accepted
activate Practitioner2
& EHR2 -> CPC2 : Task accepted
& CPC2 -> CPS : Update Task: status accepted
& CPS -> CPC1 : Notify Task update

Practitioner2 -[#purple]> EHR2 : <color #purple>Need patient\n <color #purple>contact details

& EHR2 -[#purple]> CPC2 : <color #purple>Get patient contact details
& CPC2 -[#purple]> CPS : <color #purple>Get CareTeam for\n <color #purple>url Care Provider 2
CPC2 -[#purple]> CPC1 : <color #purple>Get Patient details
CPC1 -[#purple]-> CPC2 : <color #purple>Patient details

& CPC2 -[#purple]-> EHR2 : <color #purple>Patient details

& EHR2 -[#purple]-> Practitioner2 : <color #purple>present Patient details
== waiting for Practitioner to start ==
Practitioner2 -> EHR2 : starting with Task
& EHR2 -> CPC2 : Task in-progress
& CPC2 -> CPS : Update Task: status in-progress
& CPS -> CPC1 : Notify Task update
== waiting for Practitioner to finish ==
Practitioner2 -> EHR2 : I'm done
& EHR2 -> CPC2 : Task is done
& CPC2 -> CPS : Update Task: status complete
& CPS -> CPC1 : Notify Task update
deactivate Practitioner2
@enduml
