@startuml overview-task-negotiation-1-2-careplan

skinparam roundcorner 20
skinparam defaultFontName Arial 


!pragma teoz true


box Care Provider 1 #e8d0a9
    actor "Practitioner" as P1
    participant "SCP-Contributor" as C1 #LightGray
    participant "<font color=white>SCP-Service" as S1 #Gray
end box
box Care Provider 2 #acd1e9
     participant "SCP-Contributor" as C2 #LightGray
    actor "Practitioner" as P2
end box

hide footbox

activate P1
autonumber 
P1 -[#Gray]> C1 : <color #Gray>Start Request referral
C1 -> P1 : Show CarePlans (if any)
P1 -> C1 : Selected CarePlan

& C1 -[#Gray]> S1 : <color #Gray>Create Task
' \nand CarePlan (if any)
& S1 -[#Gray]> S1  : <color #Gray>Create Subscriptions,\n update CarePlan 
 S1 o-[#Gray]> C1 : Notify CarePlan updated
& S1 o-[#Gray]> C2  : <color #Gray>Notify Task created

' autonumber 10 "<font color=Gray>0"
'  C2 -> C2 : evaluate Task:\n Need more information
' & C2 -> S1  : Create (sub-)Task2: do\n  Questionnaire 'required data'
' & S1 -> C1 : Notify Task2 created
' & C1 -> P1 : Present Questionnaire\n(prefill data from EHR)

' P1 -> C1 : Complete\n QuestionnaireResponse
' & C1 -> S1 : Update Task2: Add\n QuestionnaireResponse
' & S1 -> C2 : Notify Task2 update
' & C2 -> P2 : Notify Task2 update

autonumber 30
& C2 -[#Gray]> C2 : <color #Gray>evaluate Task:\n <color #Gray>status 'accepted'


C2 o-[#Gray]> P2 : <color #Gray>Notify Task update
& C2 o-[#Gray]> S1 : <color #Gray>Update Task: \n <color #Gray>status 'accepted'
 S1 -> S1  : Update CareTeam
S1 -[#Gray]> C1 :<color #Gray>Notify Task accepted\n CareTeam updated
& S1 o-> C2 :Notify CareTeam updated
& C1 -[#Gray]> P1 : <color #Gray>Your order \n<color #Gray>is accepted
deactivate P1

== waiting for Task to start ==
activate P2
P2 -[#Gray]> C2 : <color #Gray>starting with Task
& C2 -[#Gray]> S1 : <color #Gray>Update Task: status in-progress
& S1 -[#Gray]> C1 : <color #Gray>Notify Task update
& C1 -[#Gray]> P1 : <color #Gray>Notify Task update

== waiting for Task to finish ==
P2 -[#Gray]> C2 : <color #Gray>Task completed
& C2 -[#Gray]> S1 : <color #Gray>Update Task: status complete
 S1 -> S1  : Update CareTeam
S1 -[#Gray]> C1 :<color #Gray>Notify Task update\n CareTeam updated
& S1 o-> C2 :Notify CareTeam updated
& C1 -[#Gray]> P1 : <color #Gray>Notify Task update
deactivate P2
@enduml
