@startuml overview-task-negotiation-1-2
autonumber
!pragma teoz true

box Care Provider 1
    actor "Practitioner" as Practitioner1
    participant "Care Plan Contributor" as CPC1
    participant "Care Plan Service" as CPS
end box
box Care Provider 2
     participant "Care Plan Contributor" as CPC2
    participant "Order mgnt" as EHR2
    actor "Practitioner" as Practitioner2
end box

activate Practitioner1
Practitioner1 -> CPC1 : Start Request\nreferral
&CPC1 -> CPS : Create CarePlan\n (if non exists\n referring Patient\n and Conditions)
& note over EHR2 #WhiteSmoke
Actions in <color #purple>purple
 are optional
end note
CPC1 -> CPS : Create Task\n status requested,\n referring CarePlan\n and (Service-)Request
& CPS -> CPC2  : Notify Task created
& CPC2 -> EHR2  : Notify Task created
& EHR2 -[#purple]> EHR2 : <color #purple>evaluate Task\n <color #purple>(required data,\n <color #purple>capacity, etc)


EHR2 -[#purple]> CPC2 : <color #purple>Need more information
& CPC2 -[#purple]> CPS  : <color #purple>Create (sub-)Task2:\n <color #purple>status 'ready',\n <color #purple> Questionnaire required data\n <color #purple>in Task2.input
& CPS -[#purple]> CPC1 : <color #purple>Notify Task2 created
& CPC1 -[#purple]> Practitioner1 : <color #purple>Present Questionnaire\n<color #purple>(prefill data from EHR)

Practitioner1 -[#purple]> CPC1 : <color #purple>Complete\n <color #purple>QuestionnaireResponse
& CPC1 -[#purple]> CPS : <color #purple>Update Task2: \n <color #purple>status 'completed', Add\n <color #purple>QuestionnaireResponse\n <color #purple>to Task2.output
& CPS -[#purple]> CPC2 : <color #purple>Notify Task2 update
& CPC2 -[#purple]> EHR2 : <color #purple>Notify Task2 update
& EHR2 -[#purple]> EHR2 : <color #purple>evaluate Task\n <color #purple>(required data,\n <color #purple>capacity, etc)

EHR2 -[#purple]> CPC2 : <color #purple>need patient\n <color #purple>contact details
& CPC2 -[#purple]> CPS : <color #purple>Create (sub-)Task3: \n <color #purple>status 'ready',\n <color #purple> Questionnaire patient\n <color #purple>contact details in Task3.input
& CPS -[#purple]> CPC1 :<color #purple>Notify Task3 created
& CPC1 -[#purple]> Practitioner1 : <color #purple>Present Questionnaire\n<color #purple>(prefill data from EHR)

Practitioner1 -[#purple]> CPC1 : <color #purple>Complete\n <color #purple>QuestionnaireResponse
& CPC1 -[#purple]> CPS : <color #purple>Update Task3: \n <color #purple>status 'completed', Add\n <color #purple>QuestionnaireResponse\n <color #purple>to Task3.output
& CPS -[#purple]> CPC2 : <color #purple>Notify Task3 update
& CPC2 -[#purple]> EHR2 : <color #purple>Notify Task3 update
& EHR2 -> EHR2 : evaluate Task:\n status 'accepted'

CPC2 -> CPS : Update Task: \n status 'accepted'
& EHR2 -> CPC2 : Notify Task update
& CPS -> CPC1 : Notify Task update
& CPC1 -> Practitioner1 : Done!\nYour order has been accepted
& EHR2 -> Practitioner2 : present Task
deactivate Practitioner1

== waiting for Task to start ==
activate Practitioner2
Practitioner2 -> EHR2 : starting with Task
& EHR2 -> CPC2 : Task in-progress
& CPC2 -> CPS : Update Task: status in-progress
& CPS -> CPC1 : Notify Task update

== waiting for Task to finish ==
Practitioner2 -> EHR2 : Task done
& EHR2 -> CPC2 : Task is done
& CPC2 -> CPS : Update Task: status complete
& CPS -> CPC1 : Notify Task update
deactivate Practitioner2
@enduml
