@startuml task-negotiation-overview-1-2
autonumber


' title Use Case Home monitoring - Hospital onboarding Patient at Monitoring Clinic

box Care Provider 1
    actor "Practitioner" as Practitioner
    participant "Care Plan User" as CPU
    participant "Care Plan Service" as CPS
end box
box Care Provider 2
    participant "Care Plan Contributor" as CPC
end box

activate Practitioner
Practitioner -> CPU : Start Request\nreferral
activate CPU
CPU -> CPS : Create CarePlan\n(if non exists\nreferring Patient\nand Conditions)
CPU -> CPS : Create Task\n(status requested,\nreferring CarePlan\nand (Service-)Request)
CPS -> CPC : Notify Task creation
activate CPC
CPC -> CPS : Update Task\n(status accepted)
CPC -> CPS : Update Task\n(status accepted)
CPS -> CPU : Notify Task update
group Optional: Add PII to Task //after// Task acceptance
CPU -> CPS : Update Task (add PII)
CPS -> CPC : Notify Task update
end group
CPU -> Practitioner : Done
deactivate CPU
deactivate Practitioner
CPC -> CPS : Update Task\n(status in-progress)
CPS -> CPU : Notify Task update
CPC -> CPS : Update Task\n(status complete)
deactivate CPC
CPS -> CPU : Notify Task update