@startuml task-negotiation-overview-1-2-3

autonumber
!pragma teoz true

box Care Provider 2
    actor "Practitioner" as Practitioner1
    participant "Care Plan Contributor" as CPC1
end box
box Care Provider 1
    participant "Care Plan Service" as CPS
end box

box Care Provider 3
    participant "Care Plan Contributor" as CPC2
    participant "Order mgnt" as EHR2
    actor "Practitioner" as Practitioner2
end box



activate Practitioner1
Practitioner1 -> CPC1 : Start Request\nreferral
& CPC1 -> CPS : Create Task:\n status requested,\n referring CarePlan\n and (Service-)Request
& CPS -> CPC2  : Notify Task created
& CPC2 -> EHR2  : Notify Task created
& EHR2 -> EHR2 : check\nrequired data\n to accept Task.

EHR2 -> CPC2 : Need more information
& CPC2 -> CPS  : Update Task: status received,\n add preliminary QuestionnaireResponse\n to Task.input
& CPS -> CPC1 : Notify Task update
& CPC1 -> Practitioner1 : Present form\n(prefill data from EHR)

Practitioner1 -> CPC1 : Complete form
& CPC1 -> CPS : Update Task: Complete\n QuestionnaireResponse\n in Task.input
& CPS -> CPC2 : Notify Task update
& CPC2 -> EHR2 : Notify Task update


& EHR2 -> Practitioner2 : present Task

deactivate Practitioner1

== waiting for Practitioner to accept ==
Practitioner2 -> EHR2 : Task accepted
activate Practitioner2
& EHR2 -> CPC2 : Task accepted
& CPC2 -> CPS : Update Task: status accepted
& CPS -> CPC1 : Notify Task update

Practitioner2 -> EHR2 : Need patient\n contact details

& EHR2 -> CPC2 : Get patient contact details
& CPC2 -> CPS : Get CareTeam for\n url Care Provider 2
CPC2 -> CPC1 : Get Patient details
CPC1 --> CPC2 : Patient details

& CPC2 --> EHR2 : Patient details

& EHR2 --> Practitioner2 : present Patient details
== waiting for Practitioner to start ==
Practitioner2 -> EHR2 : starting with Task
& EHR2 -> CPC2 : Task in-progress
& CPC2 -> CPS : Update Task: status in-progress
& CPS -> CPC1 : Notify Task update
== waiting for Practitioner to finish ==
Practitioner2 -> EHR2 : I'm done
& EHR2 -> CPC2 : Task is done
& CPC2 -> CPS : Update Task: status complete
& CPS -> CPC1 : Notify Task update
deactivate Practitioner2
@enduml