@startuml task-negotiation-overview-1-2
autonumber


' title Use Case Home monitoring - Hospital onboarding Patient at Monitoring Clinic

box Care Provider 1
    actor "Practitioner" as Practitioner
    participant "CS-Selective Consumer\nCare Plan Contributor" as EHR1
    
end box

participant "Care Plan Service" as CPS
participant "CS-Selective Supplier\nCare Plan Definition Service" as CSSS
box Care Provider 2
    participant "Care Plan Contributor" as EHR2
end box

activate Practitioner
Practitioner -> EHR1 : Start Request\nreferral
activate EHR1
EHR1 -> CSSS : Search Care Plan\nDefinition
EHR1 -> CPS : Create CarePlan\n(referring Patient\nand Conditions)
EHR1 -> CSSS : Search Task Owner
EHR1 -> CPS : Create Task\n(status requested,\nreferring CarePlan\nand (Service-)Request)
CPS -> EHR2 : Notify Task creation
activate EHR2
EHR2 -> CPS : Update Task\n(status accepted)
CPS -> EHR1 : Notify Task update
EHR1 -> Practitioner : Done
deactivate EHR1
deactivate Practitioner
EHR2 -> CPS : Update Task\n(status in-progress)
CPS -> EHR1 : Notify Task update
EHR2 -> CPS : Update Task\n(status complete)
deactivate EHR2
CPS -> EHR1 : Notify Task update
@enduml