services:
  epic-fhir-inbound-adapter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - EPIC_ADAPTER_FHIR_BASEURL=https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4/
      - EPIC_ADAPTER_LISTEN_ADDRESS=:8080
      - EPIC_ADAPTER_JWK_FILE=/app/jwk.json
      - EPIC_ADAPTER_OAUTH_CLIENT_ID=${EPIC_ADAPTER_OAUTH_CLIENT_ID}
      - EPIC_ADAPTER_JWK_KEYID=${EPIC_ADAPTER_JWK_KEYID}
    volumes:
      - ./.envfiles/private.jwk:/app/jwk.json:ro