### Create a new FHIR CarePlan
POST http://localhost:8000/fhir/CarePlanService/CarePlan
Content-Type: application/json

{
  "resourceType": "CarePlan",
  "status": "active",
  "intent": "proposal",
  "activity": [],
  "subject": {
    "identifier": {
      "system": "http://fhir.nl/fhir/NamingSystem/bsn",
      "value": "1234567890"
    }
  }
}

> {%
    client.global.set('carePlanID', response.body.id)
%}


### Create a Task to be used as activity in the CarePlan
POST http://localhost:8000/fhir/CarePlanService/Task
Content-Type: application/json

{
  "resourceType": "Task",
  "status": "requested",
  "intent": "order",
  "basedOn": [{
    "reference": "CarePlan/{{carePlanID}}"
  }],
  "requester": {
     "identifier": {
        "system": "http://fhir.nl/fhir/NamingSystem/ura",
        "value": "5000"
      },
    "display": "First Organization"
  },
  "owner": {
     "identifier": {
        "system": "http://fhir.nl/fhir/NamingSystem/ura",
        "value": "2000"
      },
    "display": "Second Organization"
  },
  "code" : {
    "coding" : [{
      "system" : "http://loinc.org",
      "code" : "58410-2",
      "display" : "Compleet bloedbeeld panel in bloed d.m.v. geautomatiseerde telling"
    }]
  }
}

> {%
    client.global.set('taskID', response.body.id)
%}

### Add initial activity to CarePlan
PATCH http://localhost:8000/fhir/CarePlanService/CarePlan/{{carePlanID}}
Content-Type: application/json-patch+json

[
  {
    "op": "add",
    "path": "/activity",
    "value": [{
      "reference": {
        "reference": "Task/{{taskID}}"
      }
    }]
  }
]

### Add subsequent activity to CarePlan
PATCH http://localhost:8000/fhir/CarePlanService/CarePlan/{{carePlanID}}
Content-Type: application/json-patch+json

[
  {
    "op": "add",
    "path": "/activity/-",
    "value": [{
      "reference": {
        "reference": "Task/{{taskID}}"
      }
    }]
  }
]