Alias: $sct = http://snomed.info/sct
Alias: $loinc = http://loinc.org
Alias: $task-status = http://hl7.org/fhir/task-status
Alias: $task-intent = http://hl7.org/fhir/request-intent
Alias: $task-code = http://hl7.org/fhir/CodeSystem/task-code
Alias: $task-input-type = http://terminology.hl7.org/CodeSystem/task-input-type
Alias: $bsn = http://fhir.nl/fhir/NamingSystem/bsn
Alias: $ura = http://fhir.nl/fhir/NamingSystem/ura
Alias: $uzi = http://fhir.nl/fhir/NamingSystem/uzi
Alias: $yesnodontknow = http://hl7.org/fhir/ValueSet/yesnodontknow
Alias: $condition-code = http://hl7.org/fhir/ValueSet/condition-code
Alias: $usage-context-type = http://terminology.hl7.org/CodeSystem/usage-context-type
Alias: $FHIR-version = http://hl7.org/fhir/FHIR-version
Alias: $v3-AdministrativeGender = http://terminology.hl7.org/CodeSystem/v3-AdministrativeGender
Alias: $v3-ActCode = http://terminology.hl7.org/CodeSystem/v3-ActCode
Alias: $v3-ActReason = http://terminology.hl7.org/CodeSystem/v3-ActReason
Alias: $v3-DataOperation = http://terminology.hl7.org/CodeSystem/v3-DataOperation
Alias: $v3-NullFlavor = http://terminology.hl7.org/CodeSystem/v3-NullFlavor
Alias: $launchContext = http://hl7.org/fhir/uv/sdc/CodeSystem/launchContext
Alias: $questionnaire-item-control = http://hl7.org/fhir/questionnaire-item-control
Alias: $uuid = urn:ietf:rfc:3986
Alias: $provenance-participant-type = http://terminology.hl7.org/CodeSystem/provenance-participant-type
Alias: $unitsofmeasure = http://unitsofmeasure.org
Alias: $audit-event-type = http://terminology.hl7.org/CodeSystem/audit-event-type
Alias: $restful-interaction = http://hl7.org/fhir/restful-interaction
// Alias: $orpha = http://www.orpha.net
// Alias: $atc = http://www.whocc.no/atc

// Alias: $v3-AddressUse = http://terminology.hl7.org/CodeSystem/v3-AddressUse
// Alias: $consentscope = http://terminology.hl7.org/CodeSystem/consentscope
// Alias: $consentcategorycodes = http://terminology.hl7.org/CodeSystem/consentcategorycodes
// Alias: $v3-RoleCode = http://terminology.hl7.org/CodeSystem/v3-RoleCode
// Alias: $condition-clinical = http://terminology.hl7.org/CodeSystem/condition-clinical
// Alias: $condition-ver-status = http://terminology.hl7.org/CodeSystem/condition-ver-status

// Alias: $data-absent-reason = http://terminology.hl7.org/CodeSystem/data-absent-reason
// Alias: $allergyintolerance-verification = http://terminology.hl7.org/CodeSystem/allergyintolerance-verification
// Alias: $allergyintolerance-clinical = http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical
// Alias: $observation-category = http://terminology.hl7.org/CodeSystem/observation-category
// Alias: $organization-type = http://nictiz.nl/fhir/NamingSystem/organization-type
// Alias: $icpc-1-nl = http://hl7.org/fhir/sid/icpc-1-nl
// Alias: $uzi-rolcode = http://fhir.nl/fhir/NamingSystem/uzi-rolcode
// Alias: $v3-ObservationInterpretation = http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation
// Alias: $icd-10-nl = http://hl7.org/fhir/sid/icd-10-nl
// Alias: $v3-AdministrativeGender = http://terminology.hl7.org/CodeSystem/v3-AdministrativeGender
// Alias: $v3-MaritalStatus = http://terminology.hl7.org/CodeSystem/v3-MaritalStatus
// Alias: $v3-LanguageAbilityProficiency = http://terminology.hl7.org/CodeSystem/v3-LanguageAbilityProficiency
// Alias: $v3-LanguageAbilityMode = http://terminology.hl7.org/CodeSystem/v3-LanguageAbilityMode
// Alias: $coverage-selfpay = http://terminology.hl7.org/CodeSystem/coverage-selfpay

// Alias: $v2-0443 = http://terminology.hl7.org/CodeSystem/v2-0443
// Alias: $immunization-recommendation-status = http://terminology.hl7.org/CodeSystem/immunization-recommendation-status
// 