services:
  fhirstore:
    image: hapiproject/hapi:v7.0.3
    ports:
      - "8000:8080"
    environment:
      - hapi.fhir.fhir_version=R4
      - hapi.fhir.partitioning.allow_references_across_partitions=false
      # Required for CareTeamService subscriptions
      - hapi.fhir.subscription.resthook_enabled=true
  initializer:
    build: initializer
    environment:
      - HAPI_FHIR_BASEURL=http://fhirstore:8080/fhir
      - NUTSNODE_INTERNAL_BASEURL=http://nutsnode:8081
    depends_on:
      fhirstore:
        condition: service_started
      nutsnode:
        condition: service_healthy
  careteamservice:
    build: careteamservice
    ports:
      - "9000:8080"
    depends_on:
      # The service crashes when the FHIR store is not running,
      # so we wait for the initializer (that blocks until the FHIR Store becomes available) to complete.
      initializer:
        condition: service_completed_successfully
    environment:
      # Where to find the FHIR store to subscribe to and write CareTeam to
      - FHIR_BASEURL=http://fhirstore:8080/fhir/CarePlanService
      # Where the FHIR Subscription should post notifications
      - CARETEAMSERVICE_BASEURL=http://careteamservice:8080
  nutsnode:
    # This service uses the dev image, which creates a devtunnel to allow public access to the Nuts node.
    # This is required for the remote Discovery Service to resolve DID documents.
    image: nutsfoundation/nuts-node:dev
    ports:
      - "7080:8080"
      - "7081:8081"
    volumes:
      - "./nutsnode/discovery:/nuts/config/discovery:ro" # Required for Service Discovery of other Care Organizations
      - "./data/nutsnode/devtunnel:/devtunnel" # Required for retaining the devtunnel on restart
      - "./data/nutsnode/data:/nuts/data" # Required for retaining Nuts node data on restart
    environment:
      - NUTS_VERBOSITY=trace
      - NUTS_DATADIR=/nuts/data
      - NUTS_HTTP_INTERNAL_ADDRESS=:8081
      - NUTS_AUTH_CONTRACTVALIDATORS=dummy
      - NUTS_DISCOVERY_DEFINITIONS_DIRECTORY=/nuts/config/discovery