@nts-username = myusername
@nts-password = mypassword
###
# @name gettokenendpoint
GET https://terminologieserver.nl/auth/realms/nictiz/.well-known/openid-configuration

###
# @name getaccesstoken

@tokenendpoint = {{gettokenendpoint.response.body.token_endpoint}}

POST {{tokenendpoint}}
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=cli_client&username={{nts-username}}&password={{nts-password}}

###
@ntsaccesstoken = Bearer {{getaccesstoken.response.body.access_token}}
@system = http://snomed.info/sct

GET https://terminologieserver.nl/fhir/CodeSystem/$lookup?system={{system}}&code=195111005&property=designation
Authorization: {{ntsaccesstoken}}

###
GET https://terminologieserver.nl/fhir/CodeSystem/$lookup?system={{system}}&code=195967001&property=designation
Authorization: {{ntsaccesstoken}}
###
GET https://terminologieserver.nl/fhir/CodeSystem/$lookup?system={{system}}&code=13645005&property=designation
Authorization: {{ntsaccesstoken}}

### example to validate a code in a ValueSet
# @valueset-url = https://terminologieserver.nl/uri/vs/snomed-netherlands-all_descriptions
# GET https://terminologieserver.nl/fhir/ValueSet/$validate-code?url={{valueset-url}}&system={{system}}&code=195967001
# Authorization: {{ntsaccesstoken}}