# 1) To use requests in this file, you need to install the REST Client extension in Visual Studio Code
#
# 2) In the settings.json of the REST Client extension, add these environment variables like so:
# "rest-client.environmentVariables": {
#         "$shared": {
#             "path-to-data": "./fsh-generated/resources/"
#         },
#         "local": {
          #  "cps1-fhir-url": "http://localhost:8080/fhir/DEFAULT/",
          #   "cps1-access-token": "Basic user:password",
          #   "cpc1-fhir-url": "https://localhost:8080/fhir/CPC1/",
          #   "cpc2-fhir-url": "https://localhost:8080/fhir/CPC2/"
#         }
# }
# 
# 3) Switch between environments by clicking on the environment name in the status bar at the bottom right of the window

# Setup FHIR server: add search parameters

###

POST {{cps1-fhir-url}}/SearchParameter
Content-Type: application/fhir+json
Authorization: {{cps1-access-token}}

<@ {{path-to-data}}SearchParameter-Task-input-reference.json


###

POST {{cps1-fhir-url}}/SearchParameter
Content-Type: application/fhir+json
Authorization: {{cps1-access-token}}

<@ {{path-to-data}}SearchParameter-Task-output-reference.json

###

POST {{cps1-fhir-url}}$reindex

###

POST {{cps1-fhir-url}}$partition-management-create-partition
Content-Type: application/fhir+json
Authorization: {{cps1-access-token}}

{
  "resourceType": "Parameters",
  "parameter": [ {
    "name": "id",
    "valueInteger": 2
  }, {
    "name": "name",
    "valueCode": "CPC1"
  }]
}

###

POST {{cps1-fhir-url}}$partition-management-create-partition
Content-Type: application/fhir+json
Authorization: {{cps1-access-token}}

{
  "resourceType": "Parameters",
  "parameter": [ {
    "name": "id",
    "valueInteger": 3
  }, {
    "name": "name",
    "valueCode": "CPC2"
  }]
}

# Test requests for usecase enrollment 

###
# @name postBundleTask1

POST {{cps1-fhir-url}}
Content-Type: application/fhir+json
Authorization: {{cps1-access-token}}

<@ {{path-to-data}}Bundle-cps-bundle-01.json

###
# @name getTask1

GET {{cps1-fhir-url}}{{postBundleTask1.response.body.entry[0].response.location}}

###
@task1id = {{getTask1.response.body.id}}
@task1etag = {{getTask1.response.body.meta.versionId}}


###
# @name getPatient1

GET {{cps1-fhir-url}}{{getTask1.response.body.for.reference}}


###
# @name getServiceRequest1

GET {{cps1-fhir-url}}{{getTask1.response.body.focus.reference}}

###

@patient1id = {{getPatient1.response.body.id}}

@servicerequest1id = {{getServiceRequest1.response.body.id}}

###
# @name postSubscription1

POST {{cps1-fhir-url}}Subscription
Content-Type: application/fhir+json
Authorization: {{cps1-access-token}}

<@ {{path-to-data}}Subscription-cps-sub-hospitalx.json

###
@subscription1id = {{postSubscription1.response.body.id}}

###
# @name postSubscription2

POST {{cps1-fhir-url}}Subscription
Content-Type: application/fhir+json
Authorization: {{cps1-access-token}}

<@ {{path-to-data}}Subscription-cps-sub-medicalservicecentre.json

###
@subscription2id = {{postSubscription2.response.body.id}}

###
# @name postCareTeam1

POST {{cps1-fhir-url}}CareTeam
Content-Type: application/fhir+json
Authorization: {{cps1-access-token}}

<@ {{path-to-data}}CareTeam-cps-careteam-01.json

###

@careteam1id = {{postCareTeam1.response.body.id}}

###
# @name postCarePlan1

POST {{cps1-fhir-url}}CarePlan
Content-Type: application/fhir+json
Authorization: {{cps1-access-token}}

<@ {{path-to-data}}CarePlan-cps-careplan-01.json

###
@careplan1id = {{postCarePlan1.response.body.id}}

###
# @name postBundleTask2

POST {{cps1-fhir-url}}
Content-Type: application/fhir+json
Authorization: {{cps1-access-token}}

<@ {{path-to-data}}Bundle-cps-bundle-02.json

###
# @name getTask2

GET {{cps1-fhir-url}}{{postBundleTask2.response.body.entry[0].response.location}}

###
@task2id = {{getTask2.response.body.id}}
@task2etag = {{getTask2.response.body.meta.versionId}}


# ###
# # @name getPatient1

# GET {{cps1-fhir-url}}{{getTask1.response.body.for.reference}}

###

POST {{cps1-fhir-url}}
Content-Type: application/fhir+json
Authorization: {{cps1-access-token}}

<@ {{path-to-data}}Bundle-cps-bundle-03.json

###
POST {{cps1-fhir-url}}
Content-Type: application/fhir+json
Authorization: {{cps1-access-token}}

<@ {{path-to-data}}Bundle-cps-bundle-06.json

###

POST {{cps1-fhir-url}}
Content-Type: application/fhir+json
Authorization: {{cps1-access-token}}

<@ {{path-to-data}}Bundle-cps-bundle-07.json

###